### PR TITLE
Rc 2356 shardids

### PR DESCRIPTION
**Pull request by rsc3**
### Description

change 4 metrics files for StarAlign.WDL

1) umipercell file, add a `shard_number` column with an integer counter for the shard number, space delimited

10k_PBMC_gex_umipercell.txt

2) cell_reads file, add a column for shard_number integer counter, tab delimited

move all CBnotInPasslist rows to the top, making sure they also have the shard_number added

remove duplicate header rows

10k_PBMC_gex_cell_reads.txt

3) align features file, add column tab delimited with shard_number integer counter

10k_PBMC_gex_align_features.txt

4) summary file, add column with shard_number counter integer, comma delimited

10k_PBMC_gex_summary.txt

***there is a possibility that shard_number won't match the scatter directory structure, such as when there are 10 or more shards due to bash ordering

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by khajoue2 — APPROVED** [review]

**Review by khajoue2 — APPROVED** [review]
@rsc3 we still need to update the Optimus pipeline version and changelog

**Comment by rsc3** [comment]
> Details

Thanks. There are 4 tests that ran as a result of the StarAlign change. Should all of them be updated as well?

**Comment by rsc3** [comment]
test this please

**Review by ekiernan — APPROVED** [review]
The outputs look good! Thanks for your work on this. LGTM as soon as the branch conflicts are resolved.

**Pull request merged**
