### PR TITLE
Np add multiome plumbing json 

### PR DESCRIPTION
**Pull request by nikellepetrillo**
### Description

this pr adds a plumbing test to the multiome pipeline 

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Comment by nikellepetrillo** [comment]
truth is being updated here: 
https://cromwell.gotc-dev.broadinstitute.org/api/workflows/1/99149dc1-a931-414d-9125-12ac38d8ca3d/status

**Comment by nikellepetrillo** [comment]
retest this please

**Comment by nikellepetrillo** [comment]
retest this please

**Review by aawdeh — APPROVED** [review]
LGTM!

**Pull request merged**
