### PR TITLE
Np update snaptoolsbwa dockers

### PR DESCRIPTION
**Pull request by nikellepetrillo**
### Description

The snaptools_bwa docker needed to be updated for security vulnerabilities. This PR replaced the new snaotools_bwa docker throughout the scATAC pipeline. 

Also, we merged in https://github.com/broadinstitute/warp-tools/pull/73, which decodes the fragChrom column in the fragments.csv file. This PR incorporates those changes and adds a new verification task (CompareSnapTextFiles) that properly sorts and cuts the fragments.csv (as well as the binCounts_1000.csv) and compares these files to our truth files. This should stop the non-determinism we are seeing in our nightly tests. 

The scatac smart test will be failing on this PR because we have changed the outputs:
how the new fragment file looks:
```gsutil cat gs://broad-gotc-test-results/dev/scATAC/plumbing/2023-08-03-08-37-46/human_example/example_id_fragments.csv | head 
,fragChrom_decoded,fragStart,fragLen
0,chr3,10848827,19
1,chr9,121947213,23
2,chr7,18273907,19
3,chr3,154414156,20
4,chr10,131014570,19
```
how the old fragment file looks: 
```
,fragChrom,fragLen,fragStart
0,b'chr3',10848827,19
1,b'chr9',121947213,23
2,b'chr7',18273907,19
3,b'chr3',154414156,20
4,b'chr10',131014570,19
```

Testing the new CompareSnapTextFiles task: 
I created a custom truth branch, updated truth with the new fragments.csv output, and ran the scATAC test: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/52096/console

To make sure the test fails when it is supposed to, I manually manipulated the truth fragments.csv on my custom truth branch so that it would **not** match the test fragments.csv. This test should fail, and here is a link to the failing test: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/52095/console

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Comment by nikellepetrillo** [comment]
how to new fragment file looks:
```gsutil cat gs://broad-gotc-test-results/dev/scATAC/plumbing/2023-08-03-08-37-46/human_example/example_id_fragments.csv | head 
,fragChrom_decoded,fragStart,fragLen
0,chr3,10848827,19
1,chr9,121947213,23
2,chr7,18273907,19
3,chr3,154414156,20
4,chr10,131014570,19
```
how the old fragment file looks: 
```
,fragChrom,fragLen,fragStart
0,b'chr3',10848827,19
1,b'chr9',121947213,23
2,b'chr7',18273907,19
3,b'chr3',154414156,20
4,b'chr10',131014570,19

**Review by ekiernan — APPROVED** [review]
LGTM!

**Review by kevinpalis — APPROVED** [review]
LGTM!

**Review by jessicaway — APPROVED** [review]
👍 Thanks @nikellepetrillo!

**Comment by nikellepetrillo** [comment]
updated truth here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/52387/console

**Pull request merged**
