### PR TITLE
KM Update metrics descriptions

### PR DESCRIPTION
**Pull request by kayleemathews**
### Description

This PR is to update the Optimus metrics doc and fix issues raised in Issue https://github.com/broadinstitute/warp/issues/1079.

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Comment by ekiernan** [comment]
Thanks for reviewing this - do you think we should specify in the Program column that it's TagSort instead of WARP-tools? We could take them directly to the code at this link: https://github.com/broadinstitute/warp-tools/tree/develop/tools/TagSort.

**Review by nikellepetrillo — APPROVED** [review]
looks good!!

**Comment by kayleemathews** [comment]
@nikellepetrillo and @ekiernan Thank you for taking a look at this. 

> Thanks for reviewing this - do you think we should specify in the Program column that it's TagSort instead of WARP-tools? We could take them directly to the code at this link: https://github.com/broadinstitute/warp-tools/tree/develop/tools/TagSort.

@ekiernan Yes I think that's a good idea. I'll make that change.

> Also wonder if it would be helpful to define cell barcode and UMI - we've had folks in recent meetings kind of use them interchangeably, but here they have distinct definitions.

@ekiernan I didn't realize this was something people were confused about. If that's the case, then yes, let's definitely do that.

**Review by ekiernan — APPROVED** [review]
Thank you so much for updating this doc!

**Pull request merged**
