### PR TITLE
Making memory an optional parameter for ValidateVcf task

### PR DESCRIPTION
**Pull request by meganshand**
When running the `ReblockGvcfs` pipeline without a `calling_interval_list`, the validation occurs over the intervals from the input (unreblocked) GVCF. In this case ValidateVariants requires much more memory. This argument will allow users to be able to adjust the memory to that task as needed if they don't provide the optional `calling_interval_list`. See also this GATK issue: https://github.com/broadinstitute/gatk/issues/8608

For typical WGS GVCFs (around 4Gb inputs) using 32 Gb of memory allowed the task to pass (setting `machine_mem_mb=32000`).

### CODE REVIEW

**Comment by kayleemathews** [comment]
@meganshand we'll need to bump the pipeline version numbers in the documentation but I can take care of that

**Comment by meganshand** [comment]
@kayleemathews Thanks, I didn't realize I needed to change the versions elsewhere. I'll try to follow how you fix it to update those next time.

**Comment by nikellepetrillo** [comment]
passing scientific JG test: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/59328/console

**Review by nikellepetrillo — APPROVED** [review]

**Review by aawdeh — APPROVED** [review]
LGTM!

**Pull request merged**
