### PR TITLE
Update GATK version in gatk_baserecalibrator and gatk_applybqsr to 4.5.0.0 for GDC Somatic WGS

### PR DESCRIPTION
**Pull request by jessicaway**
…

### Description

Ticket requesting this change can be found here: https://broadinstitute.atlassian.net/browse/PO-65298?focusedCommentId=1431983

### CODE REVIEW

**Comment by nikellepetrillo** [comment]
code itself looks fine, but smart tests are unhappy :( Failing with
```Unrecognized VM option 'PrintGCTimeStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Using GATK jar /gatk/gatk-package-4.5.0.0-local.jar```

This might have to do with the java bump in one of the more recent gatk releases

**Review by kevinpalis — APPROVED** [review]

**Comment by jessicaway** [comment]
This was specifically requested by GP and identified as necessary by Chris Kachulis. We'll reach out to scientific owners to confirm any differences observed in scientific tests (adding eng-only label to this PR)

**Review by kevinpalis — APPROVED** [review]

**Review by ekiernan — APPROVED** [review]
LGTM! Thank you!

**Review by nikellepetrillo — APPROVED** [review]
looks good!

**Comment by nikellepetrillo** [comment]
GDC scientific test is running here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/63659/console

**Comment by nikellepetrillo** [comment]
New scientific test running: #6​64​82

**Pull request merged**
