### PR TITLE
staging --> master

### PR DESCRIPTION
**Pull request by ekiernan**
staging --> master

### CODE REVIEW

**Comment by ekiernan** [comment]
Updated Truth for Multiome and Optimus off of staging. Scientific tests for Multiome are running here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/77322/

Scientific test for Optimus are running here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/77323/

**Comment by ekiernan** [comment]
retest this please

**Comment by ekiernan** [comment]
WGS Metrics were validated in this [spreadsheet](https://docs.google.com/spreadsheets/d/1qLSaweBoPPIXCc-OwRQJ7UI4Oca3UvyzdP-k1OoV-SA/edit#gid=1345632044).

We confirmed that the differences in metrics were likely due to non-determinism. We reran the tests from master and saw similar failures in WGS tasks. The run scientific run from master is [here](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/77605/consoleFull).

We did find a previous PR that is supposed to remove non-determinism [here](https://github.com/broadinstitute/warp/pull/717) and we saw that we reverted this PR in a separate PR [here](https://github.com/broadinstitute/warp/pull/929) because the scientific tests were failing. We could revisit this in the future.

**Comment by ekiernan** [comment]
Paired-tag now fails because there is no scientific test provided. This will be provided on a separate release of the pipeline.

**Review by khajoue2 — APPROVED** [review]
looks good

**Review by nikellepetrillo — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Pull request merged**
