### PR TITLE
PD-2100 replace all instances of hca-dcp-mint-test-data/reference with broad-gotc-test-storage

### PR DESCRIPTION
**Pull request by nikellepetrillo**
### Description

The HCA data test needs to be moved out of buckets billing to HCA. HCA does not want to pay for storage anymore.

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [X] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by khajoue2 — APPROVED** [review]

**Comment by nikellepetrillo** [comment]
retest this please

**Review by jessicaway — APPROVED** [review]
👍

**Comment by nikellepetrillo** [comment]
scientific optimus test : https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/40824/

**Comment by nikellepetrillo** [comment]
passing scientific optimus test: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/40824/console

**Review by jessicaway — APPROVED** [review]
Looks good to me!

**Pull request merged**
