### PR TITLE
staging --> master

### PR DESCRIPTION
**Pull request by ekiernan**
staging --> master

### CODE REVIEW

**Comment by ekiernan** [comment]
Rerunning Multiome with atac_nhash_id here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/85638/

**Comment by ekiernan** [comment]
Optimus tests:
8k pbmc stranded sample: X.sum differs by 2 UMIs, gene metrics flagged, but sums match when tested manually. 

8k pbmc unstranded sample: Same errors we saw for stranded sample. Checked X.sums manually for cells and genes alone and the sums matched. 

Example:
```>>> umis_ad1 = np.array(test.X.sum(axis=0)).flatten()
>>> umis_ad2 = np.array(truth.X.sum(axis=0)).flatten()
>>> umis_equal = np.array_equal(umis_ad1, umis_ad2)
```

**Comment by jessicaway** [comment]
@broadinstitute/warp-admins (just testing)

**Comment by ekiernan** [comment]
Joint genotyping:
dev_bge failed. see gs://broad-gotc-dev-cromwell-execution/TestJointGenotyping/e6d98c0e-740b-428c-8167-4a155570faed/

**Comment by ekiernan** [comment]
retest this please

**Comment by ekiernan** [comment]
retest this please

**Comment by ekiernan** [comment]
Smart-tests rerun here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-smart-tests/8522/

As expected, Multiome failed with similar failures that we saw before in library metrics and h5ad because we added doublet info. 

Multiome truth update is here:https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/85725/parameters/

All other tests now pass because we updated truth.

**Review by rsc3 — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Pull request merged**
