### PR TITLE
Np move snm3c from beta pipelines 

### PR DESCRIPTION
**Pull request by nikellepetrillo**
### Description

This pr moves the wdized snm3c .wdl our from beta pipelines

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by kevinpalis — APPROVED** [review]
Looks good.

**Comment by nikellepetrillo** [comment]
Passing scientific snm3c test: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/64299/console

**Review by ekiernan — APPROVED** [review]
Thank you! @kayleemathews We can release documentation when this is merged.

**Comment by nikellepetrillo** [comment]
passing plumbing snm3c test: https://cromwell.gotc-dev.broadinstitute.org/api/workflows/1/b33f406f-5a88-4dfa-9be6-33be61a15139/status

**Pull request merged**
