### PR TITLE
Fix all the (scatter) things!

### PR DESCRIPTION
**Pull request by ldgauthier**
I broke the scattering.  The previous mode won't necessarily return the number of requested scatters. We need INTERVAL_SUBDIVISION mode to actually get the right number of scatters so GenomicsDB doesn't take forever.

### CODE REVIEW

**Review by khajoue2 — APPROVED** [review]
lgtm

**Comment by jessicaway** [comment]
add to whitelist

**Comment by ldgauthier** [comment]
This should incorporate the exome_joint_calling_regions.v1.1.interval_list file in #141 to get rid of the giant ICE target liftovers that cause problems for exomes

**Review by gbggrant — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Comment by gbggrant** [comment]
@ldgauthier is this still needed?

**Comment by gbggrant** [comment]
Hi @ldgauthier - should this be merged? Or was it addressed in another PR?

**Comment by ldgauthier** [comment]
To totally fix all the scatter issues a bunch of things have to happen:
Exomes:
- [ ] Why doesn't ExomeGermlineSingleSample have a sample inputs json?
- [x] add new interval list generation script
- [ ] copy new exome_calling_regions.v1.1.interval_list to GCP (PO-45720)
- [ ] Update exome single-sample json "calling_interval_list": "gs://gcp-public-data--broad-references/hg38/v0/exome_calling_regions.v1.1.interval_list",
- [ ] JointGenotyping.inputs.json gets new exome_calling_regions.v1.1.interval_list (50bp padding w/o bad ICE liftovers)
- (Note that single sample and JG use same intervals)
- [ ] Exome update doesn't _really_ need versioning because after JG territory is reduced, old GVCFs just have extra

WGS:
- [x] WGS handcrafted 20K intervals needs centromeres and telomeres removed
- [ ] copy updated intervals to GCP public data bucket (PO-45720)
- [ ] Picard PR with scatter mode update needs to be merged: https://github.com/broadinstitute/picard/pull/1786
- [ ] GATK needs to update Picard dependency and cut a release
- [ ] Scatter task in JointGenotypingTasks needs to update to new GATK; add extra arg `--dont-mix-contigs`
- [ ] Update pipelines/broad/dna_seq/germline/joint_genotyping/wgs/JointGenotyping.inputs.json  to "JointGenotyping.SplitIntervalList.scatter_mode": "INTERVAL_COUNT_WITH_DISTRIBUTED_REMAINDER",

**Comment by jessicaway** [comment]
@ldgauthier Is this PR still relevant?

**Comment by ldgauthier** [comment]
Yes.  Maybe we don't keep track of callset runtime/cost, but all of these changes should be improvements.

**Comment by jessicaway** [comment]
Great, we'll try to get this merged in soon 👍

**Comment by nikellepetrillo** [comment]
passing scientific tests: 
https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/50544/console
https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/50549/console

**Comment by nikellepetrillo** [comment]
@ldgauthier looks like warp's oldest PR is ready to be merged in 😄  Does this all look ok to you before we merge it in?

**Pull request merged**
