### PR TITLE
Delete beta-pipelines/skylab/ATAC directory

### PR DESCRIPTION
**Pull request by jpramosbarroso**
PD-2290 — we do not use the ATAC workflow in beta-pipelines. All improvement suggestions from this pipeline have already been incorporated into the new the Multiome subworkflow ATAC. Only change is the ATAC workflow being deleted from beta-pipelines folder.

[✓] Did you modify, delete or move: file paths, file names, input names, output names, or task names?

### CODE REVIEW

**Comment by jpramosbarroso** [comment]
@ekiernan @kayleemathews

**Comment by jessicaway** [comment]
Apparently we did have a test for this. We will also need to delete this directory: https://github.com/broadinstitute/warp/tree/develop/tests/skylab/ATAC/pr
(I found this by looking at the failing womtool check)

**Comment by jpramosbarroso** [comment]
ATAC testing directory has been deleted

**Comment by nikellepetrillo** [comment]
test this please

**Review by nikellepetrillo — APPROVED** [review]
looks great, thank you!

**Review by kevinpalis — APPROVED** [review]
LGTM!

**Comment by nikellepetrillo** [comment]
test this please

**Comment by nikellepetrillo** [comment]
@jpramosbarroso all of the PR tests are passing now so feel free to merge it 🎉  When you merge it, be sure to click "squash and merge" instead of  "create a merge commit". Let me know if you have any questions or issues trying to merge this in!

**Pull request merged**
