### PR TITLE
Updated a check for an empty file produced in the GetFingerprintingIntervalIndices task in JointGenotypingByChromosomePartOne.wdl.

### LINKED ISSUE #767: Check for an empty file in JointGenotypingByChromosomePartOne.wdl needs to be updated.
https://github.com/broadinstitute/warp/blob/baf72dd4adb34c38cf12e818ec4abd7ecce5d105/pipelines/broad/dna_seq/germline/joint_genotyping/by_chromosome/JointGenotypingByChromosomePartOne.wdl#L209

@snovod encountered an issue (in https://broadinstitute.atlassian.net/browse/PO-48542?atlOrigin=eyJpIjoiYTYxOGYyNjhiYWI1NGJlZTliZWRhNTE4NmUxZjFlOGUiLCJwIjoiaiJ9 ) with this condition check, which does not account for the change of behavior in `read_lines` for empty files introduced in https://github.com/broadinstitute/cromwell/pull/6457/. If that change is to be supported, we should instead check that the array is non-empty, and not that its first element is not `””`. The condition can occur when `haplotype_database` intervals and the intervals produced by concatenating the `unpadded_intervals` have no overlap.

### PR DESCRIPTION
**Pull request by samuelklee**
Closes #767.

Note that I also searched for other instances of such a file check in the repo and didn't find any.

### CODE REVIEW

**Review by kbergin — APPROVED** [review]
LGTM but I added eng from the team to review as well.

**Comment by jessicaway** [comment]
add to whitelist

**Review by snovod — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Comment by samuelklee** [comment]
Apologies @snovod and others, clearing out the backlog during the retreat and just noticed that this never got merged. I think I need to update the changelog, but will then go ahead and merge afterwards.

**Comment by samuelklee** [comment]
OK, I've updated the version/changelog. Not sure if this was actually necessary. Also not sure if I'm the one who should merge the PR---feel free to let me know if this is the case or to go ahead and merge otherwise. Sorry, new to this repo!

**Comment by samuelklee** [comment]
@snovod I've updated the version and changelog. If all looks good, please merge on my behalf!

**Pull request merged**
