### PR TITLE
Staging -> Master

### PR DESCRIPTION
**Pull request by gbggrant**

### CODE REVIEW

**Review by wjdingman1 — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Comment by gbggrant** [comment]
Smart [Tests](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-smart-tests/3019/)  failed on 4 cases:
**Arrays** - strange [failure](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19907/) with a db constraint violation. Rerunning [here](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19947/).

 **BroadInternalRNAWithUMIs** - I think this [failed](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19908/) because of the bi-weekly prod->dev db refresh. Rerunning [here](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19948/).

**WGS GermlineSingleSample** - [Failed](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19915/) with the dragenmode tests failing validation. The other 4 are normal. Strange. I think that @wjdingman1 updated truth for this recently.

RNAWithUMIs Failed validation. - [Failed](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19920/) validation. This is because I failed to update the truth (new genome-specific truth data). Updating truth [here](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/19949/).

**Comment by wjdingman1** [comment]
ill look at the wgs....thats annoying

**Comment by wjdingman1** [comment]
@gbggrant After looking at failures it looks like crais/crams are only failing on one location for each sample but multiple shards are failing with a variety of small metrics changes for both samples.

I don't know if something slipped into dev in the last few days to affect these changes or what? Do you think its okay to just update truth off whats in staging now and go from there

**Comment by gbggrant** [comment]
@wjdingman1 not sure. Let's discuss at standup.

**Comment by gbggrant** [comment]
Smart [Tests](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-smart-tests/3029/)  failed on 2 cases:

**BroadInternalRNAWithUMIs** Failed validation. - [Failed](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/20029/) validation. This is because I failed to update the truth (new genome-specific truth data). Have updated truth.  Re-Running [Here](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/20068/).

 **WGS GermlineSingleSample** - [Failed](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/20036/) with the dragenmode tests failing validation. The other 4 are normal.  We are investigating whether this is due to the new dragenemode runs yielding non-deterministic results.

**Comment by jessicaway** [comment]
I believe the rerun of BroadInternalRNAWithUMIs after the truth update is actually here:
https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/20080/

**Comment by wjdingman1** [comment]
These updates don't touch WGS. Dragen mode tests are already in master so we are good to merge.

**Pull request merged**
