### PR TITLE
update rsem_ref_index in buildIndices

### PR DESCRIPTION
**Pull request by nikellepetrillo**
rsem_ref_index should be hard coded to say "rsem" instead of "star"

### CODE REVIEW

**Comment by nikellepetrillo** [comment]
Heres a run with the new code: https://cromwell.gotc-dev.broadinstitute.org/api/workflows/1/a795b419-5a2c-483a-8818-18afcbd4befb/outputs

Old run: https://cromwell.gotc-dev.broadinstitute.org/api/workflows/1/bdcd11ab-4840-4d3c-b8c7-e61385fa2173/outputs

**Review by khajoue2 — APPROVED** [review]
lgtm

**Review by khajoue2 — APPROVED** [review]
lgtm

**Review by ekiernan — APPROVED** [review]
LGTM!

**Review by gbggrant — COMMENTED** [review]
Why is pipeline release validation failing?  Is this cause it's part of a not-yet released pipeline?

```11:18:45 BuildIndices.wdl has not had its version updated
11:18:45 grep: /home/jenkins/workspace/warp-validate-release/pipelines/skylab/build_indices/BuildIndices.changelog.md: No such file or directory```

**Comment by nikellepetrillo** [comment]
@gbggrant Yes, it is because the pipeline has not yet been released. Im not sure if we have plans to release it anytime soon? cc @kbergin

**Comment by kbergin** [comment]
I hadn't really thought about it, I don't think of it as as necessary as our other pipelines since it changes so infrequently, but if we think it's important to do we can prioritize releasing it.

**Comment by gbggrant** [comment]
Might be worth prioritizing the release to get around this error message.

**Comment by kbergin** [comment]
Have the issues in this PR since been addressed? We haven't gotten this one merged for a while but I think you've run Build Indices so that makes me wonder if they're fixed? https://github.com/broadinstitute/warp/pull/154

**Comment by kbergin** [comment]
Do we have tests for this pipeline to go with the release? I don't want that work to hold up this PR, but I'm willing to prioritize it in the future.

**Comment by nikellepetrillo** [comment]
No, we do not have tests for this pipeline.

I'm not really sure what the status of https://github.com/broadinstitute/warp/pull/154 is, but this pr would address one of his concerns ("the output file names for two tasks was identical causing errors when running cromwell with the "final_workflow_outputs_dir" option.")

**Comment by kbergin** [comment]
Ok, when this is merged could you comment on that PR and say that part of the PR made it into this update and ask for him to rebase and respond to comments so we can merge in the rest? :)

**Pull request merged**
