### PR TITLE
[GL-1591] Update Broad Images to Python 3

### PR DESCRIPTION
**Pull request by cheyenne-gold**
All broad Docker images should be updated to use Python 3. Also added some clean up to make images smaller. These images should still pass trivy scans and plumbing/scientific tests. **Note**: GOTC is not being updated to Python 3 for now, it will be addressed later.

### CODE REVIEW

**Comment by wjdingman1** [comment]
Make sure you merge this into develop instead and add your changes to the develop change logs!

**Review by wjdingman1 — COMMENTED** [review]
Looks good, just fix the merge conflicts

**Comment by jessicaway** [comment]
This looks good. Will there be a separate PR to replace the old images with the new images?

**Comment by jessicaway** [comment]
test science please

**Pull request merged**
