### PR TITLE
GDC somatic pipeline - return contamination value as a file 

### PR DESCRIPTION
**Pull request by jessicaway**

### CODE REVIEW

**Comment by jessicaway** [comment]
The tests do not automatically run for beta-pipelines. I have manually kicked off the test; it can be found [here](https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/4542/)

**Review by gbggrant — APPROVED** [review]

**Review by tbl3rd — APPROVED** [review]
Thank you.  Is `contam.txt` the traditional name?

**Comment by jessicaway** [comment]
This code came from the tag group, it looks like they named it `contam.txt`. I can rename it if there is another name you prefer

**Comment by tbl3rd** [comment]
> This code came from the tag group, it looks like they named it `contam.txt`. I can rename it if there is another name you prefer

Works for me.

**Pull request merged**
