### PR TITLE
staging --> master

### PR DESCRIPTION
**Pull request by ekiernan**
staging --> master

### CODE REVIEW

**Comment by ekiernan** [comment]
Optimus stranded differences in h5ad are because emptydrops and doublet_scores as expected. Example output of comparison script:

```
Comparing test cell metrics to truth cell metrics using truth as ref
Cell Metric Column does not match:
emptydrops_Limited
Sum of test: 
405021
Sum of truth: 
405246
Cell Metric Column does not match:
emptydrops_IsCell
Sum of test: 
8205
Sum of truth: 
8181
Cell Metric Column does not match:
emptydrops_PValue
Sum of test: 
5580.613738626135
Sum of truth: 
5571.003599640037
Cell Metric Column does not match:
emptydrops_FDR
Sum of test: 
2926.5229497384116
Sum of truth: 
2917.894627910774
Cell Metric Column does not match:
doublet_score
Sum of test: 
1197.3503134796238
Sum of truth: 
1219.707157784744
Comparing test gene metrics to truth gene metrics using truth as ref
Making gene_names unique
Done
If no warning above Done, gene metrics match now that they are unique
Testing for new obs columns in test data set:
Done
If no warning above Done, no new obs columns in test matrix
Testing for new var columns in test data set:
Done
If no warning above Done, no new var columns in test matrix
Testing matrix count sums
Counts match
```

Optimus unstranded failures are also due to expected differences. Example output:

`Comparing test cell metrics to truth cell metrics using truth as ref
Cell Metric Column does not match:
emptydrops_Limited
Sum of test: 
407815
Sum of truth: 
407802
Cell Metric Column does not match:
emptydrops_IsCell
Sum of test: 
8448
Sum of truth: 
8471
Cell Metric Column does not match:
emptydrops_PValue
Sum of test: 
4917.797220277972
Sum of truth: 
4874.906409359065
Cell Metric Column does not match:
emptydrops_FDR
Sum of test: 
3067.1602723851365
Sum of truth: 
3024.672590846901
Cell Metric Column does not match:
doublet_score
Sum of test: 
1194.6862591431554
Sum of truth: 
1207.1969696969697
Comparing test gene metrics to truth gene metrics using truth as ref
Making gene_names unique
Done
If no warning above Done, gene metrics match now that they are unique
Testing for new obs columns in test data set:
Done
If no warning above Done, no new obs columns in test matrix
Testing for new var columns in test data set:
Done
If no warning above Done, no new var columns in test matrix
Testing matrix count sums
Counts match`

**Comment by ekiernan** [comment]
Ultima failed to complete. Rerunning scientific here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/94411/

**Comment by ekiernan** [comment]
WGS failed to complete; rerunning scientific here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/94412/

**Comment by ekiernan** [comment]
Exome failures are all in the .crosscheck file for metrics - ConsolidateErrors

**Review by nikellepetrillo — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Pull request merged**
