### PR TITLE
Lk pd 2654 tso metrics

### PR DESCRIPTION
**Pull request by ekiernan**
testing

### CODE REVIEW

**Review by khajoue2 — APPROVED** [review]
Changelogs needs to be updated

**Review by kevinpalis — APPROVED** [review]
LGTM

**Comment by ekiernan** [comment]
Verified h5ad outputs for all tests; h5ads are identical except for NHashID and tso_reads.

**Comment by ekiernan** [comment]
retest this please

**Comment by ekiernan** [comment]
retest this please

**Pull request merged**
