### PR TITLE
Moved whitelist parameters as input files

### PR DESCRIPTION
**Pull request by vsmalladi**
### Description

White list was hardcoded as gs paths. Made them defaults and moved to inputs for workflow so that they will be able to be inputed for different paths for azure. 

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by kevinpalis — APPROVED** [review]
LGTM!

**Comment by jessicaway** [comment]
Hi @vsmalladi, 

I believe you are trying to make the pipeline flexible to accept whitelist files from sources other than GCP, is that correct?

The pipeline should already allow this. 

The reason the defaults are listed outside the inputs section is to have the pipeline automatically select the whitelist based on the chemistry. This behavior and defaults can be overridden by explicitly providing a whitelist as input to the pipeline. Here is the input that allows this: https://github.com/broadinstitute/warp/blob/develop/pipelines/skylab/optimus/Optimus.wdl#L38

Does that address the concern you are trying to address with this PR or is there a further issue?

**Comment by vsmalladi** [comment]
> Hi @vsmalladi,
> 
> I believe you are trying to make the pipeline flexible to accept whitelist files from sources other than GCP, is that correct?
> 
> The pipeline should already allow this.
> 
> The reason the defaults are listed outside the inputs section is to have the pipeline automatically select the whitelist based on the chemistry. This behavior and defaults can be overridden by explicitly providing a whitelist as input to the pipeline. Here is the input that allows this: https://github.com/broadinstitute/warp/blob/develop/pipelines/skylab/optimus/Optimus.wdl#L38
> 
> Does that address the concern you are trying to address with this PR or is there a further issue?

@jessicaway  I get that, but then this assumes that the person knows about the files before trying to run the pipeline. Moving it to Inputs allows the files to be known by the user and UI in terra to have a user put in Azure or other location for the reference data.

**Comment by vsmalladi** [comment]
@jessicaway yes lets do a call next week will reach out on slack.

**Comment by jessicaway** [comment]
This Pr does not appear to contain a meaningful change at this point and we have addressed this issue in separate ways

**Pull request closed without merging**
