### PR TITLE
Staging -> Master

### PR DESCRIPTION
**Pull request by gbggrant**
- Fixed error in Exome and WGS Germline Single Sample Workflow (incorrect relative import statement in Alignment subworkflow)
- Add miniwdl tool to check
- Add GDCWholeGenomeSomaticSingleSample.options workflow (beta)

### CODE REVIEW

**Review by sophiacrennan — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Comment by gbggrant** [comment]
WGS Reprocessing Test failed with transient / weird error on parsing input json.  Rerunning it at: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/3264/

**Review by nikellepetrillo — APPROVED** [review]

**Comment by kbergin** [comment]
Is this test really still running? :( Maybe next week we can release this.

**Comment by gbggrant** [comment]
yes, it really took that long.  It did finally finish running a couple of hours ago.  A couple of the WGS Reprocessing tests failed validation, but I'm pretty sure that's a transient / weird issue.  Hopefully good to release Monday or Tuesday.

**Comment by gbggrant** [comment]
Two of the verification jobs in https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/3264/  failed with errors in CompareBams that look odd.  I'm rerunning the verification at: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/3341/

**Comment by gbggrant** [comment]
Verification jobs for WGS Reprocessing finished successfully.  https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/3341/

**Pull request merged**
