### PR TITLE
Clean up all scATAC pipeline folders and workflow names

### PR DESCRIPTION
**Pull request by sophiacrennan**

### CODE REVIEW

**Comment by ekiernan** [comment]
@sophiacrennan @kbergin  Are we adding the ATAC pipeline to a beta folder now or later?

**Comment by sophiacrennan** [comment]
> @sophiacrennan @kbergin Are we adding the ATAC pipeline to a beta folder now or later?

I thought it was already in the beta folder but maybe I am mistaken.

**Comment by ekiernan** [comment]
> > @sophiacrennan @kbergin Are we adding the ATAC pipeline to a beta folder now or later?
> 
> I thought it was already in the beta folder but maybe I am mistaken.

It looks like it's in the skylab- I don't see a beta pipelines folder in the repo?

**Comment by sophiacrennan** [comment]
> > > @sophiacrennan @kbergin Are we adding the ATAC pipeline to a beta folder now or later?
> > 
> > 
> > I thought it was already in the beta folder but maybe I am mistaken.
> 
> It looks like it's in the skylab- I don't see a beta pipelines folder in the repo?

Ooh I see. I'll fix that.

**Pull request merged**
