### PR TITLE
fix: missing indexes

### PR DESCRIPTION
**Pull request by exander77**

### CODE REVIEW

**Comment by kbergin** [comment]
Hi @exander77 - thanks so much for contributing a PR. I think this was already fixed in https://github.com/broadinstitute/warp/pull/172 and is now in Develop releases. We are working on promoting it to staging and master this week and will update the releases and Terra afterwards. Let me know if this PR doesn't satisfy the bug.

**Comment by exander77** [comment]
@kbergin I can rerun my workflow if you give me a notice. And I will see if everything checks out.

**Comment by kbergin** [comment]
So sorry, I was confusing this work with the relative import bug! Ignore my last comment. @sophiacrennan has been working on fixing this bug, maybe she can compare her changes to what you've done for testing purposes.

**Comment by exander77** [comment]
@kbergin Check it, I have processed my large samples with it and it went fine with this modification.

**Comment by sophiacrennan** [comment]
@exander77 I am glad that both of our PRs have the same changes. I fixed the failing tests in my PR and will merge it up soon.

**Comment by kbergin** [comment]
https://github.com/broadinstitute/warp/pull/179 has been merged in and will be promoted and released soon. I think this PR can be closed. Thank you for submitting it, it helped us confirm that the changes made would work for your use case!

**Comment by exander77** [comment]
@kbergin Not a problem, I am glad that I made it work as well.

**Pull request closed without merging**
