### PR TITLE
added 1MM_multi option to barcode correction and updated changelogs

### PR DESCRIPTION
**Pull request by ekiernan**
### Description
This PR changes the Optimus STARsolo alignment parameters for cell barcode correction to 1MM_multi. This will impact scientific outputs. 
----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [x] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [x] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by kayleemathews — APPROVED** [review]
Thanks for updating docs @ekiernan!

**Comment by ekiernan** [comment]
Scientific tests launched here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/71662/parameters/

**Comment by ekiernan** [comment]
Optimus scientific tests here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/72041/

**Comment by ekiernan** [comment]
Running Optimus scientific here: https://gotc-jenkins.dsp-techops.broadinstitute.org/job/warp-workflow-tests/72388/

**Pull request closed without merging**
