### PR TITLE
Update task name from CheckMercuryFingerprint to CheckFingerprintTask

### PR DESCRIPTION
**Pull request by wjdingman1**

### CODE REVIEW

**Comment by kbergin** [comment]
Lol we want to remove the word Mercury, not Fingerprint. `CheckFingerprintTask`

**Comment by wjdingman1** [comment]
@gbggrant whoops that was a complete typo on part, thank you

**Comment by wjdingman1** [comment]
@kbergin @gbggrant sorry about that, typo on my part. should be fixed now

**Review by kbergin — APPROVED** [review]

**Comment by wjdingman1** [comment]
retest this please

**Pull request merged**
