### PR TITLE
PD-2483

### PR DESCRIPTION
**Pull request by rsc3**
### Description

Update Multiome metrics with aligner_metrics from Optimus

_Give your PR a **concise** yet **descriptive** title._
_Please explain the changes you made here._
_Explain the **motivation** for making this change. What existing problem does the pull request solve?_
_Mention any issues fixed, addressed, or otherwise related to this pull request, including issue numbers or hard links for issues in other repos._
_You can delete these instructions once you have written your PR description._

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [x] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [x] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Comment by kayleemathews** [comment]
@rsc3 This will require some minor documentation updates. I can take a look and make those updates today!

**Review by kayleemathews — APPROVED** [review]
Docs are updated accordingly - LGTM!

**Review by khajoue2 — APPROVED** [review]
looks good

**Review by ekiernan — APPROVED** [review]
Looks good! Thank you!

**Comment by nikellepetrillo** [comment]
add to whitelist

**Pull request merged**
