### PR TITLE
Update GATK and Picard

### PR DESCRIPTION
**Pull request by jessicaway**
Updating GATK and Picard to the latest versions with the log4j update (GATK 4.2.4.0 and Picard 2.26.8) throughout all pipelines (GATK 3 has not been updated, but contains a version of log4j that predates the vulnerability)

### CODE REVIEW

**Review by wjdingman1 — APPROVED** [review]
looks good!

**Comment by kbergin** [comment]
I'm not sure if we will need to collect this info for each scientific owner to review their pipeline, so just in case since I already pulled it together for GDC pipeline, here is the version of Picard and GATK that each task was using:

Picard 2.23.8: RevertSam, ValidateSam, SortSam, InsertSizeMetrics
Picard 2.18.11: Mark Duplicates
GATK 4.0.7.0: BQSR Recalibrator, ApplyBQSR
GATK 4.1.8.0: GetPileupSummaries, CalculateContamination

**Review by fleharty — APPROVED** [review]
This all looks fine, just version upgrades....

Is there a way to import standard dockers across a large number of WDLs?  It could save a lot of copy and pasting.  As it is, I can't really tell if any were missed.

**Comment by jessicaway** [comment]
@fleharty Thanks for taking a look!

We have gone back and forth on the idea of defining the different docker images either in the inputs or in the top level workflow as a potential way to centralize the image versions. We landed on keeping the dockers defined in the tasks however, since the tool versions are really key to validation of a release. We want to make sure any released version of the pipeline has fixed tool versions for each task.

**Comment by nikellepetrillo** [comment]
retest this please

**Comment by nikellepetrillo** [comment]
To summarize:
 Back in march, a[ google doc ](https://docs.google.com/document/d/1yGuOPyS8PCDqV2FdAUGRvP9lVvnpwgqMUEoA85Utv6U/edit#heading=h.ri7a07cufyyn) was sent out to scientific owners alerting them of changes after we updated the pipelines to GATK version 4.2.4.0 and Picard version 2.26.8.  After we were given the go ahead from scientific owners to update truth with these new GATK and Picard versions, Jess updated a custom truth branch (jw_03_09_22) with validated truth.
  
Over the last several weeks, GATK has put out a few more releases, with the latest being 4.2.6.1. We ran all of our pipelines using GATK 4.2.6.1 and validated against our previously validated truth branch, jw_03_09_22. All pipelines passed, with the exception of WGS and Exome Joint Genotyping. @ldgauthier has validated those results.

**Review by gbggrant — APPROVED** [review]

**Review by ldgauthier — APPROVED** [review]
Ship it!

**Review by kachulis — APPROVED** [review]

**Pull request merged**
