### PR TITLE
Ph pd 2086 replace loom output

### PR DESCRIPTION
**Pull request by phendriksen100**
### Description

This PR addresses the need to update the output format of our SlideSeq WDL workflow from Loom to H5AD. Previously, our workflow generated Loom files as output, but due to Loom no longer being actively supported, we are transitioning to the H5AD format.

----

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [ ] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by aawdeh — APPROVED** [review]
LGTM!

**Review by ekiernan — APPROVED** [review]
LGTM! We confirmed that the h5ad output matches Loom metrics.

**Comment by ekiernan** [comment]
retest this please

**Comment by nikellepetrillo** [comment]
retest this please

**Comment by ekiernan** [comment]
retest this please

**Comment by kayleemathews** [comment]
@phendriksen100 We definitely need to do some documentation updates with this PR. I can take a look either this afternoon or tomorrow morning!

**Pull request merged**
