### PR TITLE
Update human_v3_example.json

### PR DESCRIPTION
**Pull request by aawdeh**
Removed whitelist from the json file as it is now hardcoded in Optimus.wdl, and changed chemistry to tenx_chemistry_version and tenX_v3 to 3 as it is now also changed in Optimus.wdl.

### Checklist 
If you can answer "yes" to the following items, please add a checkmark next to the appropriate checklist item(s) **and** notify our WARP documentation team by tagging either @ekiernan or @kayleemathews in a comment on this PR.

- [ ] Did you add inputs, outputs, or tasks to a workflow?
- [X] Did you modify, delete or move: file paths, file names, input names, output names, or task names?
- [ ] If you made a changelog update, did you update the pipeline version number?

### CODE REVIEW

**Review by ekiernan — COMMENTED** [review]
@aawdeh I think it would be good to put this on the branch with the chemistry changes: https://github.com/broadinstitute/warp/tree/lk-PD-2134-optimus-chem. The tests won't pass unless the branch has the WDL changes in it too.

**Comment by aawdeh** [comment]
> @aawdeh I think it would be good to put this on the branch with the chemistry changes: https://github.com/broadinstitute/warp/tree/lk-PD-2134-optimus-chem. The tests won't pass unless the branch has the WDL changes in it too.

Sounds good. Thank you for the suggestion!

**Comment by aawdeh** [comment]
I updated the json files in the https://github.com/broadinstitute/warp/tree/lk-PD-2134-optimus-chem branch (as suggested by @ekiernan). Should I close this pull request?

**Comment by ekiernan** [comment]
> I updated the json files in the https://github.com/broadinstitute/warp/tree/lk-PD-2134-optimus-chem branch (as suggested by @ekiernan). Should I close this pull request?

@aawdeh yes, I think it's ok to close.

**Comment by aawdeh** [comment]
Closing pull request as changes were made in another branch.

**Pull request closed without merging**
