### PR TITLE
staging->master

### PR DESCRIPTION
**Pull request by kishorikonwar**

### CODE REVIEW

**Comment by gbggrant** [comment]
Note: JG Exome scientific test failed in Verification due to a permissions problem - I don't consider this a reason to stop the release (but let's wait for JG WGS to complete).

**Comment by gbggrant** [comment]
Note.  Had to merge master into staging as there was an inadvertent commit to master.

**Comment by jessicaway** [comment]
Do we not have proper branch protections on master?

**Comment by gbggrant** [comment]
Evidently not!

**Review by sophiacrennan — APPROVED** [review]

**Review by jessicaway — APPROVED** [review]

**Pull request merged**
